In [1]:
import numpy as np
import pandas as pd
from functools import reduce

In [2]:
files=['hdfc.csv','itc.csv','l&t.csv','m&m.csv','sunpha.csv','tcs.csv']
dfs=[]

for file in files:
    temp=pd.read_csv(file)
    temp.columns=['Date',file.replace('.csv','')]
    dfs.append(temp)

stocks = reduce(lambda left,right: pd.merge(left,right,on='Date'), dfs)
print(stocks.shape)
stocks.head()

(37, 7)


Date     hdfc     itc     l&t     m&m  sunpha      tcs
0  June 2018  2108.05  266.05  1271.3  896.80  560.55  1847.20
1   May 2018  2136.15  271.60  1367.6  923.50  480.15  1744.80
2   Apr 2018  1944.60  281.45  1400.6  872.65  528.15  1765.70
3   Mar 2018  1891.45  255.90  1311.9  740.20  495.40  1424.65
4   Feb 2018  1883.80  265.10  1319.1  728.75  535.35  1519.13

In [3]:
def hist_return(months):
    ''' It calculates Stock returns for various months and returns a dataframe.
        Input: Months in the form of a list.
        Output: Historical returns in the form of a DataFrame. '''
    idx=[]
    df=pd.DataFrame()
    for mon in months:
        temp=(stocks.iloc[0,1:] - stocks.iloc[mon,1:])/(stocks.iloc[mon,1:])
        idx.append(str(mon)+'_mon_return')
        df=pd.concat([df, temp.to_frame().T], ignore_index=True)
    df.index=idx
    return df    

In [4]:
hist_stock_returns=hist_return([3,6,12,24,36])
hist_stock_returns

hdfc       itc       l&t       m&m    sunpha       tcs
3_mon_return   0.114515  0.039664 -0.030947  0.211564   0.13151  0.296599
6_mon_return   0.125163  0.011212  0.011417  0.194062 -0.017957  0.368094
12_mon_return  0.275866 -0.178478  0.129783  0.330899  0.010911  0.562537
24_mon_return  0.792712  0.084237  0.274461  0.255179 -0.265911   0.44833
36_mon_return  0.974847  0.266844  0.069614  0.399938 -0.358785  0.447535

In [5]:
gene = np.random.rand()
gene

0.6030072726626011

In [6]:
import time
def gen_mc_grid(rows, cols, n, N):  # , xfname): generate monte carlo wind farm layout grids
        np.random.seed(seed=int(time.time()))  # init random seed
        layouts = np.zeros((n, rows * cols), dtype=np.int32)  # one row is a layout
        # layouts_cr = np.zeros((n*, 2), dtype=np.float32)  # layouts column row index
        positionX = np.random.randint(0, cols, size=(N * n * 2))
        positionY = np.random.randint(0, rows, size=(N * n * 2))
        ind_rows = 0  # index of layouts from 0 to n-1
        ind_pos = 0  # index of positionX, positionY from 0 to N*n*2-1
        # ind_crs = 0
        while ind_rows < n:
            layouts[ind_rows, positionX[ind_pos] + positionY[ind_pos] * cols] = 1
            if np.sum(layouts[ind_rows, :]) == N:
                # for ind in range(rows * cols):
                #     if layouts[ind_rows, ind] == 1:
                #         r_i = np.floor(ind / cols)
                #         c_i = np.floor(ind - r_i * cols)
                #         layouts_cr[ind_crs, 0] = c_i
                #         layouts_cr[ind_crs, 1] = r_i
                #         ind_crs += 1
                ind_rows += 1
            ind_pos += 1
            if ind_pos >= N * n * 2:
                print("Not enough positions")
                break
        # filename = "positions{}by{}by{}N{}.dat".format(rows, cols, n, N)
#         np.savetxt(lofname, layouts, fmt='%d', delimiter="  ")
        # np.savetxt(xfname, layouts_cr, fmt='%d', delimiter="  ")
        return layouts

def gen_mc_grid_with_NA_loc(rows, cols, n, N,NA_loc):  # , xfname): generate monte carlo wind farm layout grids
        np.random.seed(seed=int(time.time()))  # init random seed
        layouts = np.zeros((n, rows * cols), dtype=np.int32)  # one row is a layout, NA loc is 0

        layouts_NA= np.zeros((n, rows * cols), dtype=np.int32)  # one row is a layout, NA loc is 2
        for i in NA_loc:
            layouts_NA[:,i-1]=2

        # layouts_cr = np.zeros((n*, 2), dtype=np.float32)  # layouts column row index
        positionX = np.random.randint(0, cols, size=(N * n * 2))
        positionY = np.random.randint(0, rows, size=(N * n * 2))
        ind_rows = 0  # index of layouts from 0 to n-1
        ind_pos = 0  # index of positionX, positionY from 0 to N*n*2-1
        # ind_crs = 0
        N_count=0
        while ind_rows < n:
            cur_state=layouts_NA[ind_rows, positionX[ind_pos] + positionY[ind_pos] * cols]
            if cur_state!=1 and cur_state!=2:
                layouts[ind_rows, positionX[ind_pos] + positionY[ind_pos] * cols]=1
                layouts_NA[ind_rows, positionX[ind_pos] + positionY[ind_pos] * cols] = 1
                N_count+=1
                if np.sum(layouts[ind_rows, :]) == N:
                    ind_rows += 1
                    N_count=0
            ind_pos += 1
            if ind_pos >= N * n * 2:
                print("Not enough positions")
                break
        # filename = "positions{}by{}by{}N{}.dat".format(rows, cols, n, N)
#         np.savetxt(lofname, layouts, fmt='%d', delimiter="  ")
#         np.savetxt(loNAfname, layouts_NA, fmt='%d', delimiter="  ")
        # np.savetxt(xfname, layouts_cr, fmt='%d', delimiter="  ")
        return layouts,layouts_NA

In [7]:
gen_mc_grid(5, 5, 100, 50)
gen_mc_grid_with_NA_loc(5, 5, 100, 50,range(10))

Not enough positions
Not enough positions


(array([[0, 0, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[2, 2, 2, ..., 1, 1, 2],
        [2, 2, 2, ..., 0, 0, 2],
        [2, 2, 2, ..., 0, 0, 2],
        ...,
        [2, 2, 2, ..., 0, 0, 2],
        [2, 2, 2, ..., 0, 0, 2],
        [2, 2, 2, ..., 0, 0, 2]]))

In [8]:
def chromosome(n):
    ''' Generates set of random numbers whose sum is equal to 1
        Input: Number of stocks.
        Output: Array of random numbers'''
    ch = np.random.rand(n)
    return ch/sum(ch)

In [9]:
child=chromosome(6)
print(child,sum(child))

[0.21378824 0.13368054 0.1700493  0.12280773 0.19639131 0.16328287] 1.0


In [10]:
n=6 # Number of stocks = 6
pop_size=100 # initial population = 100

population = np.array([chromosome(n) for _ in range(pop_size)])
print(population.shape)
print(population)

(100, 6)
[[0.1545743  0.08776359 0.04837439 0.22267164 0.2336672  0.25294887]
 [0.23557834 0.09956653 0.11013537 0.23976711 0.14730245 0.16765019]
 [0.21217937 0.06625657 0.06587634 0.25888307 0.2551301  0.14167455]
 [0.17420555 0.22292233 0.08225937 0.05632142 0.31743124 0.14686008]
 [0.09686026 0.18813382 0.24566263 0.1136736  0.1549731  0.2006966 ]
 [0.2269158  0.07207576 0.23805289 0.03478667 0.09472715 0.33344174]
 [0.25531786 0.04900642 0.19391984 0.12780738 0.11310755 0.26084096]
 [0.04673312 0.08348231 0.14869354 0.26896604 0.28521359 0.1669114 ]
 [0.17338997 0.24018553 0.01484474 0.18296755 0.18324008 0.20537214]
 [0.16013407 0.11146773 0.23668559 0.20731414 0.15239303 0.13200543]
 [0.20833171 0.06154419 0.23166917 0.13345701 0.11008572 0.2549122 ]
 [0.18636536 0.06257701 0.19687536 0.26611803 0.11927038 0.16879385]
 [0.28843027 0.06312009 0.31529873 0.04032923 0.21307014 0.07975154]
 [0.18140911 0.15861355 0.00468267 0.22968128 0.20907339 0.21653999]
 [0.12245889 0.18743459 0

In [11]:
# Convert to numeric columns from Object datatypes.
print(hist_stock_returns.info())
cols=hist_stock_returns.columns
hist_stock_returns[cols] = hist_stock_returns[cols].apply(pd.to_numeric, errors='coerce')
print(hist_stock_returns.info())

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 3_mon_return to 36_mon_return
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   hdfc    5 non-null      object
 1   itc     5 non-null      object
 2   l&t     5 non-null      object
 3   m&m     5 non-null      object
 4   sunpha  5 non-null      object
 5   tcs     5 non-null      object
dtypes: object(6)
memory usage: 280.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 3_mon_return to 36_mon_return
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   hdfc    5 non-null      float64
 1   itc     5 non-null      float64
 2   l&t     5 non-null      float64
 3   m&m     5 non-null      float64
 4   sunpha  5 non-null      float64
 5   tcs     5 non-null      float64
dtypes: float64(6)
memory usage: 280.0+ bytes
None


In [12]:
cov_hist_return=hist_stock_returns.cov()

print(cov_hist_return)

# For ease of calculations make covariance of same variable as zero.
for i in range(6):
    cov_hist_return.iloc[i][i]=0
    
cov_hist_return

            hdfc       itc       l&t       m&m    sunpha       tcs
hdfc    0.160272  0.045393  0.027916  0.024127 -0.079078  0.014362
itc     0.045393  0.025467 -0.000718  0.004381 -0.023178 -0.005554
l&t     0.027916 -0.000718  0.014206  0.002510 -0.013841  0.007330
m&m     0.024127  0.004381  0.002510  0.007412 -0.011042  0.005700
sunpha -0.079078 -0.023178 -0.013841 -0.011042  0.041781 -0.007211
tcs     0.014362 -0.005554  0.007330  0.005700 -0.007211  0.009923


hdfc       itc       l&t       m&m    sunpha       tcs
hdfc    0.000000  0.045393  0.027916  0.024127 -0.079078  0.014362
itc     0.045393  0.000000 -0.000718  0.004381 -0.023178 -0.005554
l&t     0.027916 -0.000718  0.000000  0.002510 -0.013841  0.007330
m&m     0.024127  0.004381  0.002510  0.000000 -0.011042  0.005700
sunpha -0.079078 -0.023178 -0.013841 -0.011042  0.000000 -0.007211
tcs     0.014362 -0.005554  0.007330  0.005700 -0.007211  0.000000

In [13]:
mean_hist_return=hist_stock_returns.mean()
mean_hist_return

hdfc      0.456621
itc       0.044696
l&t       0.090865
m&m       0.278328
sunpha   -0.100047
tcs       0.424619
dtype: float64

In [14]:
sd_hist_return=hist_stock_returns.std()
sd_hist_return

hdfc      0.400340
itc       0.159583
l&t       0.119189
m&m       0.086091
sunpha    0.204405
tcs       0.099615
dtype: float64

In [15]:
def mean_portfolio_return(child):
    return np.sum(np.multiply(child,mean_hist_return))

In [16]:
mean_portfolio_return(population[0])

0.22490517594261544

In [17]:
def var_portfolio_return(child):
    part_1 = np.sum(np.multiply(child,sd_hist_return)**2)
    temp_lst=[]
    for i in range(6):
        for j in range(6):
            temp=cov_hist_return.iloc[i][j] * child[i] * child[j]
            temp_lst.append(temp)
    part_2=np.sum(temp_lst)
    return part_1+part_2

In [18]:
var_portfolio_return(population[0])

0.0035921457089583097

In [19]:
rf=7.12/100

In [20]:
def fitness_fuction(child):
    ''' This will return the Sharpe ratio for a particular portfolio.
        Input: A child/chromosome (1D Array)
        Output: Sharpe Ratio value (Scalar)'''
    return (mean_portfolio_return(child)-rf)/np.sqrt(var_portfolio_return(child))

In [21]:
fitness_fuction(population[7])

2.7302026366009113

In [22]:
def Select_elite_population(population, frac=0.3):
    ''' Select elite population from the total population based on fitness function values.
        Input: Population and fraction of population to be considered as elite.
        Output: Elite population.'''
    population = sorted(population,key = lambda x: fitness_fuction(x),reverse=True)
    percentage_elite_idx = int(np.floor(len(population)* frac))
    return population[:percentage_elite_idx]

In [23]:
print(len(Select_elite_population(population, frac=0.3)))
Select_elite_population(population, frac=0.3)

30


[array([0.03916898, 0.22485628, 0.00399854, 0.20647552, 0.24080338,
        0.2846973 ]),
 array([0.02022875, 0.17201093, 0.02384824, 0.30126337, 0.25242172,
        0.23022699]),
 array([0.02722833, 0.14297119, 0.14685317, 0.24762366, 0.21378809,
        0.22153556]),
 array([0.01353004, 0.25560387, 0.06346525, 0.25754779, 0.24299543,
        0.16685763]),
 array([0.16379065, 0.09630777, 0.05701319, 0.0939916 , 0.25773837,
        0.33115842]),
 array([0.04673312, 0.08348231, 0.14869354, 0.26896604, 0.28521359,
        0.1669114 ]),
 array([0.1545743 , 0.08776359, 0.04837439, 0.22267164, 0.2336672 ,
        0.25294887]),
 array([0.06421344, 0.17233782, 0.16430573, 0.17529322, 0.2240596 ,
        0.19979018]),
 array([0.02100244, 0.22545483, 0.0683995 , 0.26306502, 0.28714299,
        0.13493522]),
 array([0.05831867, 0.18715297, 0.21738551, 0.05376878, 0.22736623,
        0.25600783]),
 array([0.10631926, 0.00406831, 0.19221716, 0.29804783, 0.16832811,
        0.23101934]),
 array([0.

In [24]:
[fitness_fuction(x) for x in population][:3]

[2.564552062499713, 1.6237151284261178, 1.9475995635866254]

In [25]:
def mutation(parent):
    ''' Randomy choosen elements of a chromosome are swapped
        Input: Parent
        Output: Offspring (1D Array)'''
    child=parent.copy()
    n=np.random.choice(range(6),2)
    while (n[0]==n[1]):
        n=np.random.choice(range(6),2)
    child[n[0]],child[n[1]]=child[n[1]],child[n[0]]
    return child

In [26]:
mutation(population[1]),population[1]

(array([0.23557834, 0.09956653, 0.11013537, 0.14730245, 0.23976711,
        0.16765019]),
 array([0.23557834, 0.09956653, 0.11013537, 0.23976711, 0.14730245,
        0.16765019]))

In [31]:
def Heuristic_crossover(parent1,parent2):
    ''' The offsprings are created according to the equation:
            Off_spring A = Best Parent  + β ∗ ( Best Parent − Worst Parent)
            Off_spring B = Worst Parent - β ∗ ( Best Parent − Worst Parent)
                Where β is a random number between 0 and 1.
        Input: 2 Parents
        Output: 2 Children (1d Array)'''
    ff1=fitness_fuction(parent1)
    ff2=fitness_fuction(parent2)
    diff=parent1 - parent2
    beta=np.random.rand()
    if ff1>ff2:
        child1=parent1 + beta * diff
        child2=parent2 - beta * diff
    else:
        child2=parent1 + beta * diff
        child1=parent2 - beta * diff
    return child1,child2

In [36]:
for i in population[:30]:
    for j in population[:30]:
        print(Arithmetic_crossover(i,j))

(array([0.1545743 , 0.08776359, 0.04837439, 0.22267164, 0.2336672 ,
       0.25294887]), array([0.1545743 , 0.08776359, 0.04837439, 0.22267164, 0.2336672 ,
       0.25294887]))
(array([0.18897188, 0.0927756 , 0.07460059, 0.22993107, 0.19699325,
       0.21672761]), array([0.20118076, 0.09455453, 0.08390917, 0.23250769, 0.18397641,
       0.20387145]))
(array([0.1601279 , 0.08569014, 0.05006172, 0.22616272, 0.2357364 ,
       0.24222111]), array([0.20662577, 0.06833003, 0.06418901, 0.25539199, 0.2530609 ,
       0.15240231]))
(array([0.15500068, 0.09069915, 0.04911035, 0.21905863, 0.2354865 ,
       0.2506447 ]), array([0.17377917, 0.21998678, 0.08152341, 0.05993443, 0.31561195,
       0.14916426]))
(array([0.15421133, 0.08839484, 0.04961517, 0.22198613, 0.23317228,
       0.25262025]), array([0.09722323, 0.18750257, 0.24442184, 0.11435911, 0.15546802,
       0.20102523]))
(array([0.16331666, 0.08586774, 0.07129673, 0.19996604, 0.21687652,
       0.2626763 ]), array([0.21817345, 0.07397

In [33]:
def Arithmetic_crossover(parent1,parent2):
    ''' The offsprings are created according to the equation:
            Off spring A = α ∗ Parent1 + (1 −α) ∗ Parent2
            Off spring B = (1 −α) ∗ Parent1 + α ∗ Parent2
            
                Where α is a random number between 0 and 1.
        Input: 2 Parents
        Output: 2 Children (1d Array)'''
    alpha = np.random.rand()
    child1 = alpha * parent1 + (1-alpha) * parent2
    child2 = (1-alpha) * parent1 + alpha * parent2
    return child1,child2

In [35]:
Arithmetic_crossover(population[2],population[3])


(array([0.20398878, 0.10004788, 0.06941   , 0.21519247, 0.26856786,
        0.14279302]),
 array([0.18239614, 0.18913103, 0.07872571, 0.10001203, 0.30399348,
        0.14574161]))